<template>
  <div class="dashboard hr-dashboard">
    <Loading v-if="loading" />
    <div class="db-wrap">
      <section class="db-top hr-hero">
        <div class="db-heading">
          <div class="db-kicker"><span class="db-kicker-dot"></span> HUMAN RESOURCE MANAGEMENT SYSTEM</div>
          <h2 class="db-title">HR Dashboard</h2>
          <p class="db-desc">Workforce overview, employee demographics, organizational distribution and HR action items.</p>
        </div>
        <div class="db-date"><font-awesome-icon icon="calendar-alt" /> {{ currentDate }}</div>
      </section>

      <div class="hr-section-heading"><div><span class="hr-section-number">01</span><div><h3>Workforce Snapshot</h3><p>Quick indicators for today's HR operations</p></div></div></div>
      <section class="db-stats hr-kpi-grid">
        <div class="stat stat--total hr-kpi"><div class="stat-info"><span class="stat-label-top">WORKFORCE</span><span class="stat-num">{{ employees.length }}</span><span class="stat-lbl">Active Employee Records</span><span class="kpi-note"><font-awesome-icon icon="circle-check" /> Current workforce</span></div><div class="stat-icon"><font-awesome-icon icon="users" /></div></div>
        <div class="stat stat--active hr-kpi"><div class="stat-info"><span class="stat-label-top">ORGANIZATION</span><span class="stat-num">{{ departments.length }}</span><span class="stat-lbl">Departments</span><span class="kpi-note"><font-awesome-icon icon="building" /> Offices represented</span></div><div class="stat-icon"><font-awesome-icon icon="building" /></div></div>
        <div class="stat stat--dept hr-kpi"><div class="stat-info"><span class="stat-label-top">DEMOGRAPHICS</span><span class="stat-num">{{ averageAge }}</span><span class="stat-lbl">Average Employee Age</span><span class="kpi-note"><font-awesome-icon icon="user-clock" /> Based on birthdate records</span></div><div class="stat-icon"><font-awesome-icon icon="user-clock" /></div></div>
        <div class="stat stat--bday hr-kpi hr-kpi-alert"><div class="stat-info"><span class="stat-label-top">HR ACTION</span><span class="stat-num">{{ attentionCount }}</span><span class="stat-lbl">Items Requiring Attention</span><span class="kpi-note"><font-awesome-icon icon="triangle-exclamation" /> Birthdays & retirement watch</span></div><div class="stat-icon"><font-awesome-icon icon="bell" /></div></div>
      </section>

      <div class="hr-section-heading"><div><span class="hr-section-number">02</span><div><h3>Workforce Analytics</h3><p>Understand employee composition and organizational distribution</p></div></div><span class="hr-section-badge"><font-awesome-icon icon="chart-line" /> LIVE RECORDS</span></div>
      <section class="db-charts hr-chart-grid">
        <div class="card-c chart-card hr-panel"><div class="card-c__h"><div class="card-title-icon"><font-awesome-icon icon="briefcase" /></div><div><span class="card-title">Employment Status</span><small>Workforce composition by employment type</small></div></div><div class="card-c__b" ref="statusChart"></div></div>
        <div class="card-c chart-card hr-panel"><div class="card-c__h"><div class="card-title-icon"><font-awesome-icon icon="venus-mars" /></div><div><span class="card-title">Gender Distribution</span><small>Employee demographic profile</small></div></div><div class="card-c__b" ref="genderChart"></div></div>
      </section>
      <section class="card-c card-c--f chart-card dept-card hr-panel hr-department-panel"><div class="card-c__h"><div class="card-title-icon"><font-awesome-icon icon="chart-column" /></div><div><span class="card-title">Employees per Department</span><small>Distribution of active employees across offices and departments</small></div></div><div class="card-c__b" ref="deptChart"></div></section>

      <div class="hr-section-heading"><div><span class="hr-section-number">03</span><div><h3>HR Demographic Insights</h3><p>Useful indicators for workforce planning and management</p></div></div></div>
      <section class="hr-insight-grid">
        <div class="hr-insight-card"><div class="hr-insight-icon"><font-awesome-icon icon="user-group" /></div><div><span>Largest Gender Group</span><strong>{{ dominantGender }}</strong><small>{{ dominantGenderCount }} employees</small></div></div>
        <div class="hr-insight-card"><div class="hr-insight-icon"><font-awesome-icon icon="briefcase" /></div><div><span>Largest Employment Type</span><strong>{{ dominantEmployment }}</strong><small>{{ dominantEmploymentCount }} employees</small></div></div>
        <div class="hr-insight-card"><div class="hr-insight-icon"><font-awesome-icon icon="cake-candles" /></div><div><span>Birthdays Today</span><strong>{{ birthdayToday.length }}</strong><small>{{ birthdayToday.length ? 'Send greetings / acknowledge employees' : 'No birthdays today' }}</small></div></div>
        <div class="hr-insight-card"><div class="hr-insight-icon"><font-awesome-icon icon="hourglass-half" /></div><div><span>Retirement Watch</span><strong>{{ retirees.length }}</strong><small>Employees age 60–65</small></div></div>
      </section>

      <div class="hr-section-heading"><div><span class="hr-section-number">04</span><div><h3>HR Action Center</h3><p>Records that may require immediate HR attention</p></div></div></div>
      <section class="hr-action-grid">
        <div class="card-c data-card hr-panel hr-action-panel"><div class="card-c__h"><div class="card-title-icon"><font-awesome-icon icon="gift" /></div><div><span class="card-title">Birthday Today</span><small>Employees celebrating today</small></div><span class="card-c__badge">{{ birthdayToday.length }}</span></div><div class="card-c__b card-table-body"><div v-if="birthdayToday.length > 0" class="tbl-wrap"><table class="tbl"><thead><tr><th>ID</th><th>Name</th><th>Department</th><th>Position</th><th>Birthday</th><th>Age</th></tr></thead><tbody><tr v-for="emp in birthdayToday" :key="emp.empid"><td class="td-mono">{{ emp.empno }}</td><td><strong>{{ emp.fullname }}</strong></td><td>{{ emp.deptdesc || '—' }}</td><td>{{ emp.position_desc || '—' }}</td><td><span class="bdg">{{ formatDate(emp.birthdate) }}</span></td><td>{{ emp.age }}</td></tr></tbody></table></div><div v-else class="empty-bday"><font-awesome-icon icon="cake-candles" /><strong>No birthdays today</strong><span>There are no employee birthdays for today.</span></div></div></div>
        <div class="card-c data-card hr-panel hr-action-panel"><div class="card-c__h"><div class="card-title-icon"><font-awesome-icon icon="clock" /></div><div><span class="card-title">Retirement Watch</span><small>Employees approaching or at retirement age</small></div><span class="card-c__badge">{{ retirees.length }}</span></div><div class="card-c__b card-table-body"><div v-if="retirees.length > 0" class="tbl-wrap"><table class="tbl"><thead><tr><th>Name</th><th>Department</th><th>Age</th><th>Birthday</th><th>Status</th></tr></thead><tbody><tr v-for="emp in displayRetirees" :key="emp.empid"><td><strong>{{ emp.fullname }}</strong></td><td>{{ emp.deptdesc || '—' }}</td><td><span class="age-pill">{{ emp.age }}</span></td><td><span class="bdg">{{ formatMonthDay(emp.birthdate) }}</span></td><td><span v-if="emp.age > 64 && isDatePassed(emp.birthdate)" class="ret-bdg">RETIRED</span><span v-else class="ready-bdg">RETIREMENT WATCH</span></td></tr></tbody></table><div v-if="retirees.length > retireesLimit" class="exp-wrap"><button class="exp-btn" @click="retireesExpanded = !retireesExpanded"><font-awesome-icon :icon="retireesExpanded ? 'chevron-up' : 'chevron-down'" /> {{ retireesExpanded ? 'Show Less' : `Show All (${retirees.length})` }}</button></div></div><div v-else class="empty-bday"><font-awesome-icon icon="clock" /><strong>No employees in retirement watch</strong><span>There are currently no employees aged 60–65 in the active records.</span></div></div></div>
      </section>

      <div class="hr-section-heading"><div><span class="hr-section-number">05</span><div><h3>Upcoming Birthdays</h3><p>Next employees scheduled to celebrate a birthday</p></div></div><span class="hr-section-badge"><font-awesome-icon icon="calendar-days" /> NEXT 30 DAYS</span></div>
      <section class="card-c card-c--f data-card hr-panel upcoming-panel"><div class="card-c__b card-table-body"><div v-if="upcomingBirthdays.length" class="upcoming-birthday-grid"><div v-for="emp in upcomingBirthdays" :key="`up-${emp.empid}`" class="upcoming-birthday-item"><div class="upcoming-date"><strong>{{ emp.daysUntil }}</strong><small>{{ emp.daysUntil === 1 ? 'DAY' : 'DAYS' }}</small></div><div class="upcoming-person"><strong>{{ emp.fullname }}</strong><span>{{ emp.deptdesc || 'Department not specified' }}</span></div><div class="upcoming-bday"><span>{{ formatMonthDay(emp.birthdate) }}</span><small>Age {{ emp.nextAge }}</small></div></div></div><div v-else class="empty-bday"><font-awesome-icon icon="calendar-days" /><strong>No upcoming birthdays</strong><span>No employee birthdays are scheduled within the next 30 days.</span></div></div></section>
    </div>
  </div>
</template>

<script>
import axios from "axios";
import * as echarts from "echarts";
import Loading from "@/components/LoadingOverlay/Loadings";

const palette = ["#0b5ed7", "#1677ff", "#2563eb", "#3b82f6", "#1d4ed8", "#60a5fa", "#075985", "#0284c7", "#38bdf8", "#1e40af", "#2563eb", "#93c5fd"];

export default {
  components: { Loading },
  head() { return { meta: [{ hid: "description", name: "description", content: "HR Dashboard" }] }; },
  data() { return { loading: true, employees: [], departments: [], birthdayToday: [], currentDate: "", retireesLimit: 10, retireesExpanded: false, charts: [] }; },
  computed: {
    activeCount() { return this.employees.filter((e) => !e.isseparated && e.EmploymentStatus).length; },
    averageAge() { const ages = this.employees.map((e) => this.calcAge(e.birthdate)).filter((a) => a > 0 && a < 120); return ages.length ? Math.round((ages.reduce((a,b) => a+b, 0) / ages.length) * 10) / 10 : 0; },
    attentionCount() { return this.birthdayToday.length + this.retirees.length; },
    dominantGender() { return this.topKey(this.countBy(this.employees, (e) => e.genderdesc || "Unknown"), "No data"); },
    dominantGenderCount() { const map = this.countBy(this.employees, (e) => e.genderdesc || "Unknown"); return map[this.dominantGender] || 0; },
    dominantEmployment() { return this.topKey(this.countBy(this.employees, (e) => e.EmploymentStatus || "Unknown"), "No data"); },
    dominantEmploymentCount() { const map = this.countBy(this.employees, (e) => e.EmploymentStatus || "Unknown"); return map[this.dominantEmployment] || 0; },
    retirees() { return this.employees.filter((e) => { if (e.EmploymentStatus !== "Permanent" && e.EmploymentStatus !== "Co-terminous" && e.EmploymentStatus !== "Casual") return false; const age = this.calcAge(e.birthdate); return age >= 60 && age <= 65; }).map((e) => ({ ...e, age: this.calcAge(e.birthdate) })).sort((a,b) => { if (a.age !== b.age) return b.age-a.age; const da=new Date(a.birthdate), db=new Date(b.birthdate); return da.getMonth()-db.getMonth() || da.getDate()-db.getDate(); }); },
    displayRetirees() { return this.retireesExpanded ? this.retirees : this.retirees.slice(0, this.retireesLimit); },
    upcomingBirthdays() { const now=new Date(), today=new Date(now.getFullYear(),now.getMonth(),now.getDate()); return this.employees.map((e) => { if (!e.birthdate) return null; const birth=new Date(e.birthdate); if (Number.isNaN(birth.getTime())) return null; let date=new Date(now.getFullYear(),birth.getMonth(),birth.getDate()); if (date<today) date=new Date(now.getFullYear()+1,birth.getMonth(),birth.getDate()); const daysUntil=Math.round((date-today)/86400000); if(daysUntil<1||daysUntil>30)return null; return { ...e, daysUntil, nextAge:this.calcAge(e.birthdate)+1 }; }).filter(Boolean).sort((a,b)=>a.daysUntil-b.daysUntil).slice(0,12); },
  },
  created() { const d=new Date(); const months=["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"], days=["Sun","Mon","Tue","Wed","Thu","Fri","Sat"]; this.currentDate=`${days[d.getDay()]}, ${months[d.getMonth()]} ${d.getDate()}, ${d.getFullYear()}`; this.fetchData(); },
  beforeDestroy() { this.charts.forEach((chart)=>{try{chart.dispose();}catch(e){}}); this.charts=[]; },
  methods: {
    countBy(items,getter){return items.reduce((map,item)=>{const key=getter(item);map[key]=(map[key]||0)+1;return map;},{});},
    topKey(map,fallback){const keys=Object.keys(map);return keys.length?keys.sort((a,b)=>map[b]-map[a])[0]:fallback;},
    async fetchData(){this.loading=true;try{await Promise.all([this.fetchEmployees(),this.fetchDepartments()]);this.$nextTick(()=>{this.processBirthdays();this.buildCharts();});}catch(e){console.error("Dashboard fetch error:",e);}finally{this.loading=false;}},
    async fetchEmployees(){try{const res=await axios({method:"GET",url:`${this.$axios.defaults.baseURL}/employees/get-all`,params:{text:"",IsSeparated:0}});const payload=res.data;if(Array.isArray(payload))this.employees=payload;else if(payload&&Array.isArray(payload.data))this.employees=payload.data;else if(payload&&Array.isArray(payload.items))this.employees=payload.items;else this.employees=[];}catch(e){console.error("Error fetching employees:",e);this.employees=[];}},
    async fetchDepartments(){try{const res=await axios({method:"GET",url:`${this.$axios.defaults.baseURL}/file-maintenance/department/get-all`});this.departments=res.data||[];}catch(e){console.error("Error fetching departments:",e);this.departments=[];}},
    processBirthdays(){const now=new Date();this.birthdayToday=this.employees.filter((e)=>{if(!e.birthdate)return false;const d=new Date(e.birthdate);return !Number.isNaN(d.getTime())&&d.getMonth()===now.getMonth()&&d.getDate()===now.getDate();}).map((e)=>({...e,age:this.calcAge(e.birthdate)}));},
    calcAge(value){if(!value)return 0;const birth=new Date(value);if(Number.isNaN(birth.getTime()))return 0;const today=new Date();let age=today.getFullYear()-birth.getFullYear();const month=today.getMonth()-birth.getMonth();if(month<0||(month===0&&today.getDate()<birth.getDate()))age--;return age;},
    isDatePassed(value){if(!value)return false;const d=new Date(value),today=new Date();return d.getMonth()<today.getMonth()||(d.getMonth()===today.getMonth()&&d.getDate()<=today.getDate());},
    formatDate(value){if(!value)return "—";const d=new Date(value);return Number.isNaN(d.getTime())?"—":d.toLocaleDateString("en-US",{month:"short",day:"numeric",year:"numeric"});},
    formatMonthDay(value){if(!value)return "—";const d=new Date(value);return Number.isNaN(d.getTime())?"—":d.toLocaleDateString("en-US",{month:"short",day:"numeric"});},
    chartBaseOption(){return{animationDuration:650,animationEasing:"cubicOut",textStyle:{fontFamily:"Arial, sans-serif"},tooltip:{backgroundColor:"#fff",borderColor:"#dbeafe",borderWidth:1,padding:[10,14],textStyle:{color:"#17345f",fontSize:12},extraCssText:"box-shadow:0 10px 30px rgba(15,64,120,.12);border-radius:10px;"}};},
    initChart(ref){if(!this.$refs[ref])return null;const chart=echarts.init(this.$refs[ref]);this.charts.push(chart);return chart;},
    buildCharts(){this.charts.forEach((c)=>{try{c.dispose();}catch(e){}});this.charts=[];this.buildStatusChart();this.buildGenderChart();this.buildDeptChart();this.$nextTick(()=>this.resizeCharts());},
    resizeCharts(){this.charts.forEach((c)=>{try{c.resize();}catch(e){}});},
    buildStatusChart(){const map=this.countBy(this.employees,(e)=>e.EmploymentStatus||"Unknown"),keys=Object.keys(map),vals=Object.values(map),total=vals.reduce((a,b)=>a+b,0),chart=this.initChart("statusChart");if(!chart)return;chart.setOption({...this.chartBaseOption(),tooltip:{...this.chartBaseOption().tooltip,trigger:"item",formatter:(p)=>`<div style="font-weight:700;margin-bottom:4px">${p.name}</div><div>${p.value} employees &nbsp; <b>${p.percent}%</b></div>`},legend:{bottom:8,left:"center",width:"90%",textStyle:{fontSize:11,color:"#55708f",fontWeight:600},icon:"circle",itemWidth:8,itemHeight:8,itemGap:14},series:[{type:"pie",radius:["55%","76%"],center:["50%","45%"],itemStyle:{borderRadius:8,borderColor:"#fff",borderWidth:4},label:{show:true,formatter:"{d}%",fontSize:11,fontWeight:800,color:"#234a78"},labelLine:{length:8,length2:6,lineStyle:{color:"#93b4d8"}},emphasis:{scale:true,scaleSize:5,label:{show:true,fontSize:14,fontWeight:800,color:"#0b5ed7"}},data:keys.map((k,i)=>({name:k,value:map[k],itemStyle:{color:palette[i%palette.length]}}))}],graphic:[{type:"group",left:"center",top:"41%",children:[{type:"text",left:"center",top:-10,style:{text:`${total}`,fill:"#123b6d",fontSize:30,fontWeight:800,textAlign:"center"}},{type:"text",left:"center",top:25,style:{text:"EMPLOYEES",fill:"#7a94b0",fontSize:9,fontWeight:700,textAlign:"center"}}]}]});},
    buildGenderChart(){const map=this.countBy(this.employees,(e)=>e.genderdesc||"Unknown"),keys=Object.keys(map),total=Object.values(map).reduce((a,b)=>a+b,0),chart=this.initChart("genderChart");if(!chart)return;chart.setOption({...this.chartBaseOption(),tooltip:{...this.chartBaseOption().tooltip,trigger:"item",formatter:(p)=>`<div style="font-weight:700;margin-bottom:4px">${p.name}</div><div>${p.value} employees &nbsp; <b>${p.percent}%</b></div>`},legend:{bottom:8,left:"center",textStyle:{fontSize:11,color:"#55708f",fontWeight:600},icon:"circle",itemWidth:8,itemHeight:8,itemGap:18},series:[{type:"pie",radius:["55%","76%"],center:["50%","45%"],itemStyle:{borderRadius:8,borderColor:"#fff",borderWidth:4},label:{show:true,formatter:"{b}\n{d}%",fontSize:11,fontWeight:800,color:"#234a78",lineHeight:16},labelLine:{length:8,length2:6,lineStyle:{color:"#93b4d8"}},emphasis:{scale:true,scaleSize:5,label:{show:true,fontSize:13,fontWeight:800,color:"#0b5ed7"}},data:keys.map((k,i)=>({name:k,value:map[k],itemStyle:{color:["#0b5ed7","#60a5fa","#bfdbfe"][i]||palette[i%palette.length]}}))}],graphic:[{type:"group",left:"center",top:"41%",children:[{type:"text",left:"center",top:-10,style:{text:`${total}`,fill:"#123b6d",fontSize:30,fontWeight:800,textAlign:"center"}},{type:"text",left:"center",top:25,style:{text:"EMPLOYEES",fill:"#7a94b0",fontSize:9,fontWeight:700,textAlign:"center"}}]}]});},
    buildDeptChart(){const empMap=this.countBy(this.employees,(e)=>e.deptdesc||"Unknown"),allDepts=this.departments.length?[...new Set([...this.departments.map((d)=>d.deptdesc),...Object.keys(empMap)])]:Object.keys(empMap),sorted=allDepts.sort((a,b)=>(empMap[b]||0)-(empMap[a]||0)),labels=sorted,vals=sorted.map((d)=>empMap[d]||0),chart=this.initChart("deptChart");if(!chart)return;chart.setOption({...this.chartBaseOption(),tooltip:{...this.chartBaseOption().tooltip,trigger:"axis",axisPointer:{type:"shadow"},formatter:(params)=>{const p=params[0];return `<div style="font-weight:700;margin-bottom:4px">${p.name}</div><div>${p.value} employees</div>`;}},grid:{left:"2%",right:"4%",top:"5%",bottom:"18%",containLabel:true},xAxis:{type:"category",data:labels,axisLabel:{color:"#64748b",fontSize:10,interval:0,rotate:labels.length>8?28:0},axisLine:{lineStyle:{color:"#dbe5f0"}},axisTick:{show:false}},yAxis:{type:"value",minInterval:1,axisLabel:{color:"#7a8ba3",fontSize:10},splitLine:{lineStyle:{color:"#edf2f7"}},axisLine:{show:false}},series:[{type:"bar",data:vals.map((v,i)=>({value:v,itemStyle:{color:palette[i%palette.length],borderRadius:[7,7,0,0]}})),barMaxWidth:42,showBackground:true,backgroundStyle:{color:"#f4f7fb",borderRadius:[7,7,0,0]},label:{show:true,position:"top",color:"#345273",fontSize:10,fontWeight:700}}]});},
  },
};
</script>
